// <auto-generated />
namespace Rezervigo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class finalupdateforforeign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finalupdateforforeign));
        
        string IMigrationMetadata.Id
        {
            get { return "202001251623178_final update for foreign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
